---
- name: Create app dir
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: 'Copy backend build folder to EC2 instance'
  become: true
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/app

- name: 'list dirs'
  become: true
  command: "ls /home/ubuntu/app"


- name: 'clean up pm2 running apps'
  become: true
  command: pm2 delete all
  ignore_errors: true

- name: 'show env'
  shell: env

- name: 'pm2 run backend process'
  become: true
  shell: pm2 start ./main.js
  args:
    chdir: /home/ubuntu/app/dist
  environment:
    ENVIRONMENT: production
    # TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    TYPEORM_CONNECTION: postgres
    # TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    TYPEORM_ENTITIES: "/home/ubuntu/app/dist/modules/domain/**/*.entity{.ts,.js}"
    # TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
    TYPEORM_MIGRATIONS_DIR: "/home/ubuntu/app/dist/migrations"
    # TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS: "/home/ubuntu/app/dist/migrations/*.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"